### ISSUE TITLE
Weird artifacts on map inside the Deku Tree

### ISSUE THREAD

**Issue by Wesley107772** [blawar/ooot#126]
## Current Behavior

Opening the map in the Deku Tree shows weird artifacts on 1F and B2.
Screenshots:
![ooot-map-issues-dekutree](https://user-images.githubusercontent.com/88684291/153681427-5bfe0c81-a8e3-4270-9f33-556b3615a0eb.jpg)

## Expected Behavior

No artifacts.

## Steps to Reproduce

1. Go to map 66 (Inside the Deku Tree)
2. Open the map.
3. Check 1F and B2.

**Comment by Dewey-Wilkerson** [comment]
Still occurs with Retail
![Base Profile Screenshot 2022 02 13 - 03 36 58 75](https://user-images.githubusercontent.com/17395556/153745789-ea883cf1-f57b-447b-8451-a2f0dc7e5ffd.png)

**Comment by DaMarkov** [comment]
I have a solution for this, but it might be better/cleaner to fix this when exporting assets.
The problem is that textures like `gDekuTreePauseScreenMapBasement2LeftTex` are completely empty.
MSVC detects that and puts these textures in special location in memory. When sending them gliden64 the issue above arises.

**Comment by blawar** [comment]
fixed
