### ISSUE TITLE
Big Rolling Goron in Goron City as Child rolls slower than normal in debug rom.

### ISSUE THREAD

**Issue by Lehpumeh** [blawar/ooot#162]
## Current Behavior

The rolling goron rolls slower than he should
## Expected Behavior

Should roll faster
## Steps to Reproduce

1. Enter Goron City and observe rolling goron on the lower floor

https://user-images.githubusercontent.com/99471756/154585911-5d6a8d28-c7ea-42cd-b654-a4cf20103f85.mp4

**Comment by DaMarkov** [comment]
We could fix this manually, but I guess this is a bug in ZAPD.
Relevant scene is `spot18_room_3ActorList_000074`.
In `EnGo2_Init` `actor.params` has the wrong value.
The speed of the goron gets set in `EnGo2_GetTargetXZSpeed`

`s32 index = pthis->actor.params & 0x1F;`
index is 0, I believe it should be 1.
Second byte of `params` must be `???00001` instead of `11111100`,

**Comment by Zero3K** [comment]
@Lehpumeh wrote in Discord that it has been fixed on PAL.
