### ISSUE TITLE
Crash going into castle town at night

### ISSUE THREAD

**Issue by ungaDamage** [blawar/ooot#40]
https://user-images.githubusercontent.com/98857629/152077108-661eb2a7-36c3-4e17-b309-c53906c80c31.mp4

https://user-images.githubusercontent.com/98857629/152077110-48398db6-9658-4550-a2f7-cb6190538db1.mp4

**Comment by Zero3K** [comment]
It might be related to #41.

**Comment by DaMarkov** [comment]
I am sure this is not related to #41 
The crash happens because in the function `Path_GetByIndex` (called because of the dog actor) on the line
`path = &globalCtx->setupPathList[index];` reads outside of the array which reads garbage data and puts it into `path` for the actor `z_en_dog.c`.

A quick hotfix would be to change the line to
`path = &globalCtx->setupPathList[0];`
This will certainly not work for scenes with multiple path lists. The night market scene only has one path list, so I am not sure why this function get called with `index > 0` or why it even works on N64

Does anyone know how `Path_GetByIndex` is supposed to work?

https://user-images.githubusercontent.com/35939509/152595894-39ad7367-4a52-4f9e-9bf9-d94bc3588365.mp4

.

**Comment by DaMarkov** [comment]
Can confirm that this has been fixed (assets need to be extracted again). Issue can be closed.
