### ISSUE TITLE
Crash upon reading the records in link's house

### ISSUE THREAD

**Issue by ungaDamage** [blawar/ooot#41]
Upon closing this textbox, the game crashes. Relatively new save file.
![link house records crash](https://user-images.githubusercontent.com/98857629/152078183-c98e93a7-36e2-41f3-8496-9f0103c21f1a.PNG)

**Comment by DaMarkov** [comment]
The crash happens because in the file z_message_PAL.c in line 1597:

`Font_LoadChar(font, temp_s2 - ' ', charTexIdx);`

`temp_s2` is actually `'\0'`. Changing the line above from:
`} else if (temp_s2 != ' ') {`
to
`} else if (temp_s2 != ' ' && temp_s2) {`

avoids this crash (surely this can only be considered a hotfix, I am not sure what `Message_Decode()` precisely does).
With this patch, the game then continues to the next textbox and then softlocks.

**Comment by blawar** [comment]
issue should be fixed, re-open if it persists.

**Comment by mrneo240** [comment]
incorrect fix

**Comment by Zero3K** [comment]
When will the correct fix be implemented?

**Comment by mrneo240** [comment]
> When will the correct fix be implemented?

I posted a patch directly to @blawar that so far has fixed these issues listed.
